export const NOT_FOUND = "NOT_FOUND";
export const BAD_REQUEST = "BAD_REQUEST";
export const DUPLICATE_ENTRY = "DUPLICATE_ENTRY";
export const NOT_UNIQUE = "NOT_UNIQUE";
export const AUTH_ERROR = "AUTH_ERROR";
export const FACEBOOK_ID_NOT_FOUND = "FACEBOOK_ID_NOT_FOUND";

export const FACEBOOK_ID_NOT_UNIQUE = "FACEBOOK_ID_NOT_UNIQUE";
export const EMAIL_NOT_UNIQUE = "EMAIL_NOT_UNIQUE";
export const EMAIL_NOT_VALID = "EMAIL_NOT_VALID";
export const PHONE_NOT_UNIQUE = "PHONE_NOT_UNIQUE";
export const WEB_ADDRESS_NOT_UNIQUE = "WEB_ADDRESS_NOT_UNIQUE";
